# https://grafana.com/docs/loki/latest/clients/promtail/configuration/#example-docker-config
server:
  disable: true

positions:
  filename: positions.yml

clients:
- url: ${LOKI_URL}
  basic_auth:
    username: ${LOKI_BASIC_AUTH_USERNAME}
    password: ${LOKI_BASIC_AUTH_PASSWORD}

scrape_configs:

- job_name: system
  static_configs:
  - targets:
     - localhost
    labels:
      customer: ${CUSTOMER}
      instance: ${INSTANCE}
      job: varlogs
      __path__: /var/log/**/*.log
      __path_exclude__: /var/log/Xorg*

# - job_name: containers
#   docker_sd_configs:
#     - host: "unix:///var/run/docker.sock"
#   relabel_configs:
#     - target_label: 'customer'
#       replacement: '${CUSTOMER}'
#     - target_label: 'instance'
#       replacement: '${INSTANCE}'
#     - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
#       target_label: 'compose_service'
#     - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
#       target_label: 'compose_project_name'
#     - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
#       target_label: 'compose_project_name'
